//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("VideoGameStoreModel", "FK_Accessory_Product", "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WCFDataServices.Product), "Accessory", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WCFDataServices.Accessory))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("VideoGameStoreModel", "FK_Console_Product", "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WCFDataServices.Product), "Console", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WCFDataServices.Console))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("VideoGameStoreModel", "FK_Purchase_Customer", "Customer", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WCFDataServices.Customer), "Purchase", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WCFDataServices.Purchase))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("VideoGameStoreModel", "FK_Game_Product", "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WCFDataServices.Product), "Game", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WCFDataServices.Game))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("VideoGameStoreModel", "FK_Product_ProductType", "ProductType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WCFDataServices.ProductType), "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WCFDataServices.Product))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("VideoGameStoreModel", "FK_Product_Supplier", "Supplier", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WCFDataServices.Supplier), "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WCFDataServices.Product))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("VideoGameStoreModel", "FK_PurchaseItem_Product", "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WCFDataServices.Product), "PurchaseItem", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WCFDataServices.PurchaseItem))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("VideoGameStoreModel", "FK_PurchaseItem_Purchase", "Purchase", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WCFDataServices.Purchase), "PurchaseItem", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WCFDataServices.PurchaseItem))]

// Original file name:
// Generation date: 3/4/2010 11:49:51 PM
namespace WCFDataServices
{
    
    /// <summary>
    /// There are no comments for VideoGameStoreEntities in the schema.
    /// </summary>
    public partial class VideoGameStoreEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new VideoGameStoreEntities object using the connection string found in the 'VideoGameStoreEntities' section of the application configuration file.
        /// </summary>
        public VideoGameStoreEntities() : 
                base("name=VideoGameStoreEntities", "VideoGameStoreEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new VideoGameStoreEntities object.
        /// </summary>
        public VideoGameStoreEntities(string connectionString) : 
                base(connectionString, "VideoGameStoreEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new VideoGameStoreEntities object.
        /// </summary>
        public VideoGameStoreEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "VideoGameStoreEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Accessory in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Accessory> Accessory
        {
            get
            {
                if ((this._Accessory == null))
                {
                    this._Accessory = base.CreateQuery<Accessory>("[Accessory]");
                }
                return this._Accessory;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Accessory> _Accessory;
        /// <summary>
        /// There are no comments for Console in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Console> Console
        {
            get
            {
                if ((this._Console == null))
                {
                    this._Console = base.CreateQuery<Console>("[Console]");
                }
                return this._Console;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Console> _Console;
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Customer> Customer
        {
            get
            {
                if ((this._Customer == null))
                {
                    this._Customer = base.CreateQuery<Customer>("[Customer]");
                }
                return this._Customer;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Customer> _Customer;
        /// <summary>
        /// There are no comments for Game in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Game> Game
        {
            get
            {
                if ((this._Game == null))
                {
                    this._Game = base.CreateQuery<Game>("[Game]");
                }
                return this._Game;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Game> _Game;
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Product> Product
        {
            get
            {
                if ((this._Product == null))
                {
                    this._Product = base.CreateQuery<Product>("[Product]");
                }
                return this._Product;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Product> _Product;
        /// <summary>
        /// There are no comments for ProductType in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ProductType> ProductType
        {
            get
            {
                if ((this._ProductType == null))
                {
                    this._ProductType = base.CreateQuery<ProductType>("[ProductType]");
                }
                return this._ProductType;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ProductType> _ProductType;
        /// <summary>
        /// There are no comments for Purchase in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Purchase> Purchase
        {
            get
            {
                if ((this._Purchase == null))
                {
                    this._Purchase = base.CreateQuery<Purchase>("[Purchase]");
                }
                return this._Purchase;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Purchase> _Purchase;
        /// <summary>
        /// There are no comments for PurchaseItem in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PurchaseItem> PurchaseItem
        {
            get
            {
                if ((this._PurchaseItem == null))
                {
                    this._PurchaseItem = base.CreateQuery<PurchaseItem>("[PurchaseItem]");
                }
                return this._PurchaseItem;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PurchaseItem> _PurchaseItem;
        /// <summary>
        /// There are no comments for Supplier in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Supplier> Supplier
        {
            get
            {
                if ((this._Supplier == null))
                {
                    this._Supplier = base.CreateQuery<Supplier>("[Supplier]");
                }
                return this._Supplier;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Supplier> _Supplier;
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((this._sysdiagrams == null))
                {
                    this._sysdiagrams = base.CreateQuery<sysdiagrams>("[sysdiagrams]");
                }
                return this._sysdiagrams;
            }
        }
        private global::System.Data.Objects.ObjectQuery<sysdiagrams> _sysdiagrams;
        /// <summary>
        /// There are no comments for Accessory in the schema.
        /// </summary>
        public void AddToAccessory(Accessory accessory)
        {
            base.AddObject("Accessory", accessory);
        }
        /// <summary>
        /// There are no comments for Console in the schema.
        /// </summary>
        public void AddToConsole(Console console)
        {
            base.AddObject("Console", console);
        }
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        public void AddToCustomer(Customer customer)
        {
            base.AddObject("Customer", customer);
        }
        /// <summary>
        /// There are no comments for Game in the schema.
        /// </summary>
        public void AddToGame(Game game)
        {
            base.AddObject("Game", game);
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public void AddToProduct(Product product)
        {
            base.AddObject("Product", product);
        }
        /// <summary>
        /// There are no comments for ProductType in the schema.
        /// </summary>
        public void AddToProductType(ProductType productType)
        {
            base.AddObject("ProductType", productType);
        }
        /// <summary>
        /// There are no comments for Purchase in the schema.
        /// </summary>
        public void AddToPurchase(Purchase purchase)
        {
            base.AddObject("Purchase", purchase);
        }
        /// <summary>
        /// There are no comments for PurchaseItem in the schema.
        /// </summary>
        public void AddToPurchaseItem(PurchaseItem purchaseItem)
        {
            base.AddObject("PurchaseItem", purchaseItem);
        }
        /// <summary>
        /// There are no comments for Supplier in the schema.
        /// </summary>
        public void AddToSupplier(Supplier supplier)
        {
            base.AddObject("Supplier", supplier);
        }
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    }
    /// <summary>
    /// There are no comments for VideoGameStoreModel.Accessory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="VideoGameStoreModel", Name="Accessory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Accessory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Accessory object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="systemName">Initial value of SystemName.</param>
        public static Accessory CreateAccessory(int productID, string systemName)
        {
            Accessory accessory = new Accessory();
            accessory.ProductID = productID;
            accessory.SystemName = systemName;
            return accessory;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this.ReportPropertyChanging("ProductID");
                this._ProductID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductID");
                this.OnProductIDChanged();
            }
        }
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property SystemName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemName
        {
            get
            {
                return this._SystemName;
            }
            set
            {
                this.OnSystemNameChanging(value);
                this.ReportPropertyChanging("SystemName");
                this._SystemName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SystemName");
                this.OnSystemNameChanged();
            }
        }
        private string _SystemName;
        partial void OnSystemNameChanging(string value);
        partial void OnSystemNameChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_Accessory_Product", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Product Product
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("VideoGameStoreModel.FK_Accessory_Product", "Product").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("VideoGameStoreModel.FK_Accessory_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Product> ProductReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("VideoGameStoreModel.FK_Accessory_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Product>("VideoGameStoreModel.FK_Accessory_Product", "Product", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for VideoGameStoreModel.Console in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="VideoGameStoreModel", Name="Console")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Console : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Console object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="driveType">Initial value of DriveType.</param>
        /// <param name="driveSize">Initial value of DriveSize.</param>
        public static Console CreateConsole(int productID, string driveType, double driveSize)
        {
            Console console = new Console();
            console.ProductID = productID;
            console.DriveType = driveType;
            console.DriveSize = driveSize;
            return console;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this.ReportPropertyChanging("ProductID");
                this._ProductID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductID");
                this.OnProductIDChanged();
            }
        }
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property DriveType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DriveType
        {
            get
            {
                return this._DriveType;
            }
            set
            {
                this.OnDriveTypeChanging(value);
                this.ReportPropertyChanging("DriveType");
                this._DriveType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("DriveType");
                this.OnDriveTypeChanged();
            }
        }
        private string _DriveType;
        partial void OnDriveTypeChanging(string value);
        partial void OnDriveTypeChanged();
        /// <summary>
        /// There are no comments for Property DriveSize in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double DriveSize
        {
            get
            {
                return this._DriveSize;
            }
            set
            {
                this.OnDriveSizeChanging(value);
                this.ReportPropertyChanging("DriveSize");
                this._DriveSize = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DriveSize");
                this.OnDriveSizeChanged();
            }
        }
        private double _DriveSize;
        partial void OnDriveSizeChanging(double value);
        partial void OnDriveSizeChanged();
        /// <summary>
        /// There are no comments for Property ConsoleDetails in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsoleDetails
        {
            get
            {
                return this._ConsoleDetails;
            }
            set
            {
                this.OnConsoleDetailsChanging(value);
                this.ReportPropertyChanging("ConsoleDetails");
                this._ConsoleDetails = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ConsoleDetails");
                this.OnConsoleDetailsChanged();
            }
        }
        private string _ConsoleDetails;
        partial void OnConsoleDetailsChanging(string value);
        partial void OnConsoleDetailsChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_Console_Product", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Product Product
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("VideoGameStoreModel.FK_Console_Product", "Product").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("VideoGameStoreModel.FK_Console_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Product> ProductReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("VideoGameStoreModel.FK_Console_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Product>("VideoGameStoreModel.FK_Console_Product", "Product", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for VideoGameStoreModel.Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomerID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="VideoGameStoreModel", Name="Customer")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Customer : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of CustomerID.</param>
        /// <param name="customerName">Initial value of CustomerName.</param>
        public static Customer CreateCustomer(int customerID, string customerName)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            customer.CustomerName = customerName;
            return customer;
        }
        /// <summary>
        /// There are no comments for Property CustomerID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this.ReportPropertyChanging("CustomerID");
                this._CustomerID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CustomerID");
                this.OnCustomerIDChanged();
            }
        }
        private int _CustomerID;
        partial void OnCustomerIDChanging(int value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property CustomerName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this._CustomerName;
            }
            set
            {
                this.OnCustomerNameChanging(value);
                this.ReportPropertyChanging("CustomerName");
                this._CustomerName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CustomerName");
                this.OnCustomerNameChanged();
            }
        }
        private string _CustomerName;
        partial void OnCustomerNameChanging(string value);
        partial void OnCustomerNameChanged();
        /// <summary>
        /// There are no comments for Property CustomerAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAddress
        {
            get
            {
                return this._CustomerAddress;
            }
            set
            {
                this.OnCustomerAddressChanging(value);
                this.ReportPropertyChanging("CustomerAddress");
                this._CustomerAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CustomerAddress");
                this.OnCustomerAddressChanged();
            }
        }
        private string _CustomerAddress;
        partial void OnCustomerAddressChanging(string value);
        partial void OnCustomerAddressChanged();
        /// <summary>
        /// There are no comments for Property CustomerDetails in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerDetails
        {
            get
            {
                return this._CustomerDetails;
            }
            set
            {
                this.OnCustomerDetailsChanging(value);
                this.ReportPropertyChanging("CustomerDetails");
                this._CustomerDetails = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CustomerDetails");
                this.OnCustomerDetailsChanged();
            }
        }
        private string _CustomerDetails;
        partial void OnCustomerDetailsChanging(string value);
        partial void OnCustomerDetailsChanged();
        /// <summary>
        /// There are no comments for Property CustomerMembershipId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> CustomerMembershipId
        {
            get
            {
                return this._CustomerMembershipId;
            }
            set
            {
                this.OnCustomerMembershipIdChanging(value);
                this.ReportPropertyChanging("CustomerMembershipId");
                this._CustomerMembershipId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CustomerMembershipId");
                this.OnCustomerMembershipIdChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _CustomerMembershipId;
        partial void OnCustomerMembershipIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCustomerMembershipIdChanged();
        /// <summary>
        /// There are no comments for Purchase in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_Purchase_Customer", "Purchase")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Purchase> Purchase
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Purchase>("VideoGameStoreModel.FK_Purchase_Customer", "Purchase");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Purchase>("VideoGameStoreModel.FK_Purchase_Customer", "Purchase", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for VideoGameStoreModel.Game in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="VideoGameStoreModel", Name="Game")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Game : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Game object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="systemName">Initial value of SystemName.</param>
        /// <param name="gameVersion">Initial value of GameVersion.</param>
        public static Game CreateGame(int productID, string systemName, byte[] gameVersion)
        {
            Game game = new Game();
            game.ProductID = productID;
            game.SystemName = systemName;
            game.GameVersion = gameVersion;
            return game;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this.ReportPropertyChanging("ProductID");
                this._ProductID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductID");
                this.OnProductIDChanged();
            }
        }
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property SystemName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemName
        {
            get
            {
                return this._SystemName;
            }
            set
            {
                this.OnSystemNameChanging(value);
                this.ReportPropertyChanging("SystemName");
                this._SystemName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SystemName");
                this.OnSystemNameChanged();
            }
        }
        private string _SystemName;
        partial void OnSystemNameChanging(string value);
        partial void OnSystemNameChanged();
        /// <summary>
        /// There are no comments for Property Rating in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Rating
        {
            get
            {
                return this._Rating;
            }
            set
            {
                this.OnRatingChanging(value);
                this.ReportPropertyChanging("Rating");
                this._Rating = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Rating");
                this.OnRatingChanged();
            }
        }
        private string _Rating;
        partial void OnRatingChanging(string value);
        partial void OnRatingChanged();
        /// <summary>
        /// There are no comments for Property Genre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre
        {
            get
            {
                return this._Genre;
            }
            set
            {
                this.OnGenreChanging(value);
                this.ReportPropertyChanging("Genre");
                this._Genre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Genre");
                this.OnGenreChanged();
            }
        }
        private string _Genre;
        partial void OnGenreChanging(string value);
        partial void OnGenreChanged();
        /// <summary>
        /// There are no comments for Property Publisher in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher
        {
            get
            {
                return this._Publisher;
            }
            set
            {
                this.OnPublisherChanging(value);
                this.ReportPropertyChanging("Publisher");
                this._Publisher = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Publisher");
                this.OnPublisherChanged();
            }
        }
        private string _Publisher;
        partial void OnPublisherChanging(string value);
        partial void OnPublisherChanged();
        /// <summary>
        /// There are no comments for Property Developer in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Developer
        {
            get
            {
                return this._Developer;
            }
            set
            {
                this.OnDeveloperChanging(value);
                this.ReportPropertyChanging("Developer");
                this._Developer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Developer");
                this.OnDeveloperChanged();
            }
        }
        private string _Developer;
        partial void OnDeveloperChanging(string value);
        partial void OnDeveloperChanged();
        /// <summary>
        /// There are no comments for Property RatingUrl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingUrl
        {
            get
            {
                return this._RatingUrl;
            }
            set
            {
                this.OnRatingUrlChanging(value);
                this.ReportPropertyChanging("RatingUrl");
                this._RatingUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("RatingUrl");
                this.OnRatingUrlChanged();
            }
        }
        private string _RatingUrl;
        partial void OnRatingUrlChanging(string value);
        partial void OnRatingUrlChanged();
        /// <summary>
        /// There are no comments for Property PlayerInfo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerInfo
        {
            get
            {
                return this._PlayerInfo;
            }
            set
            {
                this.OnPlayerInfoChanging(value);
                this.ReportPropertyChanging("PlayerInfo");
                this._PlayerInfo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PlayerInfo");
                this.OnPlayerInfoChanged();
            }
        }
        private string _PlayerInfo;
        partial void OnPlayerInfoChanging(string value);
        partial void OnPlayerInfoChanged();
        /// <summary>
        /// There are no comments for Property GameVersion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] GameVersion
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._GameVersion);
            }
            set
            {
                this.OnGameVersionChanging(value);
                this.ReportPropertyChanging("GameVersion");
                this._GameVersion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("GameVersion");
                this.OnGameVersionChanged();
            }
        }
        private byte[] _GameVersion;
        partial void OnGameVersionChanging(byte[] value);
        partial void OnGameVersionChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_Game_Product", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Product Product
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("VideoGameStoreModel.FK_Game_Product", "Product").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("VideoGameStoreModel.FK_Game_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Product> ProductReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("VideoGameStoreModel.FK_Game_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Product>("VideoGameStoreModel.FK_Game_Product", "Product", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for VideoGameStoreModel.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="VideoGameStoreModel", Name="Product")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Product : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="productName">Initial value of ProductName.</param>
        /// <param name="productDescription">Initial value of ProductDescription.</param>
        /// <param name="listPrice">Initial value of ListPrice.</param>
        /// <param name="listPriceCurrency">Initial value of ListPriceCurrency.</param>
        /// <param name="productVersion">Initial value of ProductVersion.</param>
        public static Product CreateProduct(int productID, string productName, string productDescription, double listPrice, string listPriceCurrency, byte[] productVersion)
        {
            Product product = new Product();
            product.ProductID = productID;
            product.ProductName = productName;
            product.ProductDescription = productDescription;
            product.ListPrice = listPrice;
            product.ListPriceCurrency = listPriceCurrency;
            product.ProductVersion = productVersion;
            return product;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this.ReportPropertyChanging("ProductID");
                this._ProductID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductID");
                this.OnProductIDChanged();
            }
        }
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                this.ReportPropertyChanging("ProductName");
                this._ProductName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProductName");
                this.OnProductNameChanged();
            }
        }
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property ProductDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDescription
        {
            get
            {
                return this._ProductDescription;
            }
            set
            {
                this.OnProductDescriptionChanging(value);
                this.ReportPropertyChanging("ProductDescription");
                this._ProductDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProductDescription");
                this.OnProductDescriptionChanged();
            }
        }
        private string _ProductDescription;
        partial void OnProductDescriptionChanging(string value);
        partial void OnProductDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ListPrice in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double ListPrice
        {
            get
            {
                return this._ListPrice;
            }
            set
            {
                this.OnListPriceChanging(value);
                this.ReportPropertyChanging("ListPrice");
                this._ListPrice = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ListPrice");
                this.OnListPriceChanged();
            }
        }
        private double _ListPrice;
        partial void OnListPriceChanging(double value);
        partial void OnListPriceChanged();
        /// <summary>
        /// There are no comments for Property ReleaseDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ReleaseDate
        {
            get
            {
                return this._ReleaseDate;
            }
            set
            {
                this.OnReleaseDateChanging(value);
                this.ReportPropertyChanging("ReleaseDate");
                this._ReleaseDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ReleaseDate");
                this.OnReleaseDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ReleaseDate;
        partial void OnReleaseDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnReleaseDateChanged();
        /// <summary>
        /// There are no comments for Property ProductImageUrl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductImageUrl
        {
            get
            {
                return this._ProductImageUrl;
            }
            set
            {
                this.OnProductImageUrlChanging(value);
                this.ReportPropertyChanging("ProductImageUrl");
                this._ProductImageUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ProductImageUrl");
                this.OnProductImageUrlChanged();
            }
        }
        private string _ProductImageUrl;
        partial void OnProductImageUrlChanging(string value);
        partial void OnProductImageUrlChanged();
        /// <summary>
        /// There are no comments for Property ListPriceCurrency in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ListPriceCurrency
        {
            get
            {
                return this._ListPriceCurrency;
            }
            set
            {
                this.OnListPriceCurrencyChanging(value);
                this.ReportPropertyChanging("ListPriceCurrency");
                this._ListPriceCurrency = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ListPriceCurrency");
                this.OnListPriceCurrencyChanged();
            }
        }
        private string _ListPriceCurrency;
        partial void OnListPriceCurrencyChanging(string value);
        partial void OnListPriceCurrencyChanged();
        /// <summary>
        /// There are no comments for Property ProductVersion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ProductVersion
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._ProductVersion);
            }
            set
            {
                this.OnProductVersionChanging(value);
                this.ReportPropertyChanging("ProductVersion");
                this._ProductVersion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProductVersion");
                this.OnProductVersionChanged();
            }
        }
        private byte[] _ProductVersion;
        partial void OnProductVersionChanging(byte[] value);
        partial void OnProductVersionChanged();
        /// <summary>
        /// There are no comments for Accessory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_Accessory_Product", "Accessory")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Accessory Accessory
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Accessory>("VideoGameStoreModel.FK_Accessory_Product", "Accessory").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Accessory>("VideoGameStoreModel.FK_Accessory_Product", "Accessory").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Accessory in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Accessory> AccessoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Accessory>("VideoGameStoreModel.FK_Accessory_Product", "Accessory");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Accessory>("VideoGameStoreModel.FK_Accessory_Product", "Accessory", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Console in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_Console_Product", "Console")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Console Console
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Console>("VideoGameStoreModel.FK_Console_Product", "Console").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Console>("VideoGameStoreModel.FK_Console_Product", "Console").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Console in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Console> ConsoleReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Console>("VideoGameStoreModel.FK_Console_Product", "Console");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Console>("VideoGameStoreModel.FK_Console_Product", "Console", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Game in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_Game_Product", "Game")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Game Game
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Game>("VideoGameStoreModel.FK_Game_Product", "Game").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Game>("VideoGameStoreModel.FK_Game_Product", "Game").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Game in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Game> GameReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Game>("VideoGameStoreModel.FK_Game_Product", "Game");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Game>("VideoGameStoreModel.FK_Game_Product", "Game", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ProductType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_Product_ProductType", "ProductType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ProductType ProductType
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ProductType>("VideoGameStoreModel.FK_Product_ProductType", "ProductType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ProductType>("VideoGameStoreModel.FK_Product_ProductType", "ProductType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ProductType in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ProductType> ProductTypeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ProductType>("VideoGameStoreModel.FK_Product_ProductType", "ProductType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ProductType>("VideoGameStoreModel.FK_Product_ProductType", "ProductType", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Supplier in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_Product_Supplier", "Supplier")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Supplier Supplier
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Supplier>("VideoGameStoreModel.FK_Product_Supplier", "Supplier").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Supplier>("VideoGameStoreModel.FK_Product_Supplier", "Supplier").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Supplier in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Supplier> SupplierReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Supplier>("VideoGameStoreModel.FK_Product_Supplier", "Supplier");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Supplier>("VideoGameStoreModel.FK_Product_Supplier", "Supplier", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PurchaseItem in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_PurchaseItem_Product", "PurchaseItem")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PurchaseItem> PurchaseItem
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PurchaseItem>("VideoGameStoreModel.FK_PurchaseItem_Product", "PurchaseItem");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PurchaseItem>("VideoGameStoreModel.FK_PurchaseItem_Product", "PurchaseItem", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for VideoGameStoreModel.ProductType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductTypeID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="VideoGameStoreModel", Name="ProductType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ProductType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ProductType object.
        /// </summary>
        /// <param name="productTypeID">Initial value of ProductTypeID.</param>
        /// <param name="productTypeName">Initial value of ProductTypeName.</param>
        /// <param name="productTypeDescription">Initial value of ProductTypeDescription.</param>
        public static ProductType CreateProductType(int productTypeID, string productTypeName, string productTypeDescription)
        {
            ProductType productType = new ProductType();
            productType.ProductTypeID = productTypeID;
            productType.ProductTypeName = productTypeName;
            productType.ProductTypeDescription = productTypeDescription;
            return productType;
        }
        /// <summary>
        /// There are no comments for Property ProductTypeID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductTypeID
        {
            get
            {
                return this._ProductTypeID;
            }
            set
            {
                this.OnProductTypeIDChanging(value);
                this.ReportPropertyChanging("ProductTypeID");
                this._ProductTypeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductTypeID");
                this.OnProductTypeIDChanged();
            }
        }
        private int _ProductTypeID;
        partial void OnProductTypeIDChanging(int value);
        partial void OnProductTypeIDChanged();
        /// <summary>
        /// There are no comments for Property ProductTypeName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductTypeName
        {
            get
            {
                return this._ProductTypeName;
            }
            set
            {
                this.OnProductTypeNameChanging(value);
                this.ReportPropertyChanging("ProductTypeName");
                this._ProductTypeName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProductTypeName");
                this.OnProductTypeNameChanged();
            }
        }
        private string _ProductTypeName;
        partial void OnProductTypeNameChanging(string value);
        partial void OnProductTypeNameChanged();
        /// <summary>
        /// There are no comments for Property ProductTypeDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductTypeDescription
        {
            get
            {
                return this._ProductTypeDescription;
            }
            set
            {
                this.OnProductTypeDescriptionChanging(value);
                this.ReportPropertyChanging("ProductTypeDescription");
                this._ProductTypeDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProductTypeDescription");
                this.OnProductTypeDescriptionChanged();
            }
        }
        private string _ProductTypeDescription;
        partial void OnProductTypeDescriptionChanging(string value);
        partial void OnProductTypeDescriptionChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_Product_ProductType", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Product> Product
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Product>("VideoGameStoreModel.FK_Product_ProductType", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Product>("VideoGameStoreModel.FK_Product_ProductType", "Product", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for VideoGameStoreModel.Purchase in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PurchaseID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="VideoGameStoreModel", Name="Purchase")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Purchase : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Purchase object.
        /// </summary>
        /// <param name="purchaseID">Initial value of PurchaseID.</param>
        /// <param name="purchaseDate">Initial value of PurchaseDate.</param>
        public static Purchase CreatePurchase(int purchaseID, global::System.DateTime purchaseDate)
        {
            Purchase purchase = new Purchase();
            purchase.PurchaseID = purchaseID;
            purchase.PurchaseDate = purchaseDate;
            return purchase;
        }
        /// <summary>
        /// There are no comments for Property PurchaseID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PurchaseID
        {
            get
            {
                return this._PurchaseID;
            }
            set
            {
                this.OnPurchaseIDChanging(value);
                this.ReportPropertyChanging("PurchaseID");
                this._PurchaseID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PurchaseID");
                this.OnPurchaseIDChanged();
            }
        }
        private int _PurchaseID;
        partial void OnPurchaseIDChanging(int value);
        partial void OnPurchaseIDChanged();
        /// <summary>
        /// There are no comments for Property PurchaseDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime PurchaseDate
        {
            get
            {
                return this._PurchaseDate;
            }
            set
            {
                this.OnPurchaseDateChanging(value);
                this.ReportPropertyChanging("PurchaseDate");
                this._PurchaseDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PurchaseDate");
                this.OnPurchaseDateChanged();
            }
        }
        private global::System.DateTime _PurchaseDate;
        partial void OnPurchaseDateChanging(global::System.DateTime value);
        partial void OnPurchaseDateChanged();
        /// <summary>
        /// There are no comments for Property Details in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this._Details;
            }
            set
            {
                this.OnDetailsChanging(value);
                this.ReportPropertyChanging("Details");
                this._Details = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Details");
                this.OnDetailsChanged();
            }
        }
        private string _Details;
        partial void OnDetailsChanging(string value);
        partial void OnDetailsChanged();
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_Purchase_Customer", "Customer")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Customer Customer
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Customer>("VideoGameStoreModel.FK_Purchase_Customer", "Customer").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Customer>("VideoGameStoreModel.FK_Purchase_Customer", "Customer").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Customer>("VideoGameStoreModel.FK_Purchase_Customer", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Customer>("VideoGameStoreModel.FK_Purchase_Customer", "Customer", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PurchaseItem in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_PurchaseItem_Purchase", "PurchaseItem")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PurchaseItem> PurchaseItem
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PurchaseItem>("VideoGameStoreModel.FK_PurchaseItem_Purchase", "PurchaseItem");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PurchaseItem>("VideoGameStoreModel.FK_PurchaseItem_Purchase", "PurchaseItem", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for VideoGameStoreModel.PurchaseItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PurchaseItemID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="VideoGameStoreModel", Name="PurchaseItem")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PurchaseItem : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PurchaseItem object.
        /// </summary>
        /// <param name="purchaseItemID">Initial value of PurchaseItemID.</param>
        /// <param name="price">Initial value of Price.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        /// <param name="discount">Initial value of Discount.</param>
        public static PurchaseItem CreatePurchaseItem(int purchaseItemID, decimal price, int quantity, double discount)
        {
            PurchaseItem purchaseItem = new PurchaseItem();
            purchaseItem.PurchaseItemID = purchaseItemID;
            purchaseItem.Price = price;
            purchaseItem.Quantity = quantity;
            purchaseItem.Discount = discount;
            return purchaseItem;
        }
        /// <summary>
        /// There are no comments for Property PurchaseItemID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PurchaseItemID
        {
            get
            {
                return this._PurchaseItemID;
            }
            set
            {
                this.OnPurchaseItemIDChanging(value);
                this.ReportPropertyChanging("PurchaseItemID");
                this._PurchaseItemID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PurchaseItemID");
                this.OnPurchaseItemIDChanged();
            }
        }
        private int _PurchaseItemID;
        partial void OnPurchaseItemIDChanging(int value);
        partial void OnPurchaseItemIDChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this.ReportPropertyChanging("Price");
                this._Price = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Price");
                this.OnPriceChanged();
            }
        }
        private decimal _Price;
        partial void OnPriceChanging(decimal value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this.ReportPropertyChanging("Quantity");
                this._Quantity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Quantity");
                this.OnQuantityChanged();
            }
        }
        private int _Quantity;
        partial void OnQuantityChanging(int value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property Discount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double Discount
        {
            get
            {
                return this._Discount;
            }
            set
            {
                this.OnDiscountChanging(value);
                this.ReportPropertyChanging("Discount");
                this._Discount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Discount");
                this.OnDiscountChanged();
            }
        }
        private double _Discount;
        partial void OnDiscountChanging(double value);
        partial void OnDiscountChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_PurchaseItem_Product", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Product Product
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("VideoGameStoreModel.FK_PurchaseItem_Product", "Product").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("VideoGameStoreModel.FK_PurchaseItem_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Product> ProductReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("VideoGameStoreModel.FK_PurchaseItem_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Product>("VideoGameStoreModel.FK_PurchaseItem_Product", "Product", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Purchase in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_PurchaseItem_Purchase", "Purchase")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Purchase Purchase
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Purchase>("VideoGameStoreModel.FK_PurchaseItem_Purchase", "Purchase").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Purchase>("VideoGameStoreModel.FK_PurchaseItem_Purchase", "Purchase").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Purchase in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Purchase> PurchaseReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Purchase>("VideoGameStoreModel.FK_PurchaseItem_Purchase", "Purchase");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Purchase>("VideoGameStoreModel.FK_PurchaseItem_Purchase", "Purchase", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for VideoGameStoreModel.Supplier in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SupplierID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="VideoGameStoreModel", Name="Supplier")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Supplier : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Supplier object.
        /// </summary>
        /// <param name="supplierID">Initial value of SupplierID.</param>
        /// <param name="supplierName">Initial value of SupplierName.</param>
        /// <param name="supplierVersion">Initial value of SupplierVersion.</param>
        public static Supplier CreateSupplier(int supplierID, string supplierName, byte[] supplierVersion)
        {
            Supplier supplier = new Supplier();
            supplier.SupplierID = supplierID;
            supplier.SupplierName = supplierName;
            supplier.SupplierVersion = supplierVersion;
            return supplier;
        }
        /// <summary>
        /// There are no comments for Property SupplierID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierID
        {
            get
            {
                return this._SupplierID;
            }
            set
            {
                this.OnSupplierIDChanging(value);
                this.ReportPropertyChanging("SupplierID");
                this._SupplierID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SupplierID");
                this.OnSupplierIDChanged();
            }
        }
        private int _SupplierID;
        partial void OnSupplierIDChanging(int value);
        partial void OnSupplierIDChanged();
        /// <summary>
        /// There are no comments for Property SupplierName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName
        {
            get
            {
                return this._SupplierName;
            }
            set
            {
                this.OnSupplierNameChanging(value);
                this.ReportPropertyChanging("SupplierName");
                this._SupplierName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SupplierName");
                this.OnSupplierNameChanged();
            }
        }
        private string _SupplierName;
        partial void OnSupplierNameChanging(string value);
        partial void OnSupplierNameChanged();
        /// <summary>
        /// There are no comments for Property SupplierAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierAddress
        {
            get
            {
                return this._SupplierAddress;
            }
            set
            {
                this.OnSupplierAddressChanging(value);
                this.ReportPropertyChanging("SupplierAddress");
                this._SupplierAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SupplierAddress");
                this.OnSupplierAddressChanged();
            }
        }
        private string _SupplierAddress;
        partial void OnSupplierAddressChanging(string value);
        partial void OnSupplierAddressChanged();
        /// <summary>
        /// There are no comments for Property SupplierPhone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierPhone
        {
            get
            {
                return this._SupplierPhone;
            }
            set
            {
                this.OnSupplierPhoneChanging(value);
                this.ReportPropertyChanging("SupplierPhone");
                this._SupplierPhone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SupplierPhone");
                this.OnSupplierPhoneChanged();
            }
        }
        private string _SupplierPhone;
        partial void OnSupplierPhoneChanging(string value);
        partial void OnSupplierPhoneChanged();
        /// <summary>
        /// There are no comments for Property SupplierVersion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SupplierVersion
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._SupplierVersion);
            }
            set
            {
                this.OnSupplierVersionChanging(value);
                this.ReportPropertyChanging("SupplierVersion");
                this._SupplierVersion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SupplierVersion");
                this.OnSupplierVersionChanged();
            }
        }
        private byte[] _SupplierVersion;
        partial void OnSupplierVersionChanging(byte[] value);
        partial void OnSupplierVersionChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("VideoGameStoreModel", "FK_Product_Supplier", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Product> Product
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Product>("VideoGameStoreModel.FK_Product_Supplier", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Product>("VideoGameStoreModel.FK_Product_Supplier", "Product", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for VideoGameStoreModel.sysdiagrams in the schema.
    /// </summary>
    /// <KeyProperties>
    /// diagram_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="VideoGameStoreModel", Name="sysdiagrams")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class sysdiagrams : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of name.</param>
        /// <param name="principal_id">Initial value of principal_id.</param>
        /// <param name="diagram_id">Initial value of diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(string name, int principal_id, int diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property principal_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int principal_id
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this.Onprincipal_idChanging(value);
                this.ReportPropertyChanging("principal_id");
                this._principal_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("principal_id");
                this.Onprincipal_idChanged();
            }
        }
        private int _principal_id;
        partial void Onprincipal_idChanging(int value);
        partial void Onprincipal_idChanged();
        /// <summary>
        /// There are no comments for Property diagram_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int diagram_id
        {
            get
            {
                return this._diagram_id;
            }
            set
            {
                this.Ondiagram_idChanging(value);
                this.ReportPropertyChanging("diagram_id");
                this._diagram_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("diagram_id");
                this.Ondiagram_idChanged();
            }
        }
        private int _diagram_id;
        partial void Ondiagram_idChanging(int value);
        partial void Ondiagram_idChanged();
        /// <summary>
        /// There are no comments for Property version in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> version
        {
            get
            {
                return this._version;
            }
            set
            {
                this.OnversionChanging(value);
                this.ReportPropertyChanging("version");
                this._version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("version");
                this.OnversionChanged();
            }
        }
        private global::System.Nullable<int> _version;
        partial void OnversionChanging(global::System.Nullable<int> value);
        partial void OnversionChanged();
        /// <summary>
        /// There are no comments for Property definition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] definition
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._definition);
            }
            set
            {
                this.OndefinitionChanging(value);
                this.ReportPropertyChanging("definition");
                this._definition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("definition");
                this.OndefinitionChanged();
            }
        }
        private byte[] _definition;
        partial void OndefinitionChanging(byte[] value);
        partial void OndefinitionChanged();
    }
}
